### PR TITLE
Engine 1.0

### PR DESCRIPTION
**Pull request by PaablooCH**

### CODE REVIEW

**Review by markmeliaa — APPROVED** [review]

**Review by gerard-queralt — APPROVED** [review]

**Review by MacXxs — APPROVED** [review]

**Review by totisama — APPROVED** [review]

**Review by AuxPort66 — APPROVED** [review]
GOOO

**Review by Dedado3000 — APPROVED** [review]
Good changes

**Review by OriolSors — APPROVED** [review]
Reviewed on Discord! Good job everyone

**Review by UriMurcia — APPROVED** [review]
OGO

**Pull request merged**
